# Generated by Django 3.1.5 on 2021-02-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Widget',
            new_name='Wacky',
        ),
    ]
